### PR TITLE
Add a fun command to generate a dad joke

### PR DESCRIPTION
**Pull request by mohammed-elhaouari**
## Description

In the same spirit, I have added a new command, to generate a silly dad joke. `/dadjoke`

## Preview
image

as always feel free to merge or leave the PR, no grudge :)

### CODE REVIEW

**Review by abdelghanimeliani — COMMENTED** [review]
hey @mohammed-elhaouari  i like the idea , but i have a question , are all the jokes respects our server's rools ?

**Comment by mohammed-elhaouari** [comment]
@abdelghanimeliani Hmm, I have checked like 10 to 20 jokes I haven't found any nsfw jokes, but it's random so I don't really know. we can replace the api though with a `JSON` file. or a small database. 

or maybe a better option would be to allow certain roles to submit jokes, and for others to consume those jokes ? what do you think ?

**Comment by abdelghanimeliani** [comment]
@mohammed-elhaouari  i think a JSON file will be better the a  database , what do you think ?

**Comment by mohammed-elhaouari** [comment]
@abdelghanimeliani yeah a JSON file would be much better in this case. let me see what can I do.

**Review by abdelghanimeliani — APPROVED** [review]

**Comment by mohammed-elhaouari** [comment]
Thanks @abdelghanimeliani

**Pull request merged**
